# Generated by Django 5.2.8 on 2025-12-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_user_alter_userrole_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
