# Generated by Django 5.2.8 on 2025-12-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_user_alter_customer_table_shopkeeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='adhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='shopkeepers_docs/'),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='adhar_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
