# Generated by Django 5.2.8 on 2025-12-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending_score',
            field=models.FloatField(default=0),
        ),
    ]
