# Generated by Django 6.0.1 on 2026-02-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to='profile/'),
        ),
    ]
